server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false